#!/bin/bash
rm -rf dist
export PYTHONHASHSEED=22
VERSION=`git describe --tags`
pyinstaller --noconfirm --ascii --name $VERSION contrib/osx.spec
hdiutil create -fs HFS+ -volname "Electrum-XZC" -srcfolder dist/Electrum-XZC.app dist/electrum-xzc-$VERSION.dmg
