#!/usr/bin/env python3

import sys
from electrum_acm import Network
from electrum_acm.util import json_encode, print_msg
from electrum_acm import bitcoin

try:
    addr = sys.argv[1]
except Exception:
    print("usage: get_history <zcoin_address>")
    sys.exit(1)

n = Network()
n.start()
_hash = bitcoin.address_to_scripthash(addr)
h = n.synchronous_get(('blockchain.scripthash.get_history',[_hash]))
print_msg(json_encode(h))
